% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
]{article}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother

\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{caption}
\usepackage{anyfontsize}
\usepackage{booktabs}
\usepackage{float}
\floatplacement{table}{H}
\makeatletter
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\makeatletter
\@ifpackageloaded{tcolorbox}{}{\usepackage[skins,breakable]{tcolorbox}}
\makeatother
\makeatletter
\@ifundefined{shadecolor}{\definecolor{shadecolor}{rgb}{.97, .97, .97}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\makeatother
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Analysis of Factors Influencing Philippine Family Population Based on GLM},
  pdfauthor={Group\_03},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{Analysis of Factors Influencing Philippine Family Population
Based on GLM}
\author{Group\_03}
\date{}

\begin{document}
\maketitle
\ifdefined\Shaded\renewenvironment{Shaded}{\begin{tcolorbox}[borderline west={3pt}{0pt}{shadecolor}, interior hidden, sharp corners, frame hidden, enhanced, boxrule=0pt, breakable]}{\end{tcolorbox}}\fi

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

In Philippine, \textbf{FIES}(Family Income and Expenditure Survey),
which is undertaken every three years, is aimed at providing data on
family income and expenditure. This dataset, comes from the FIES
recorded in the Philippines, is analysed in this report.

In particular, this report presents numerical and graphical summaries of
FIES and fits a \textbf{Generalized Linear Model(GLM)} with
\textbf{Poisson Regression} to analyze which household related variables
influence the number of people living in a household.

\hypertarget{research-question}{%
\section{Research Question}\label{research-question}}

Which household related variables influence the number of people living
in a household?

\hypertarget{data-cleaning}{%
\section{Data Cleaning}\label{data-cleaning}}

First read the data and tidy the data using tidyverse:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Read the data set}
\NormalTok{Data\_FIES }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"dataset03.csv"}\NormalTok{)}
\CommentTok{\# Tidy the data}
\NormalTok{FIES }\OtherTok{\textless{}{-}}\NormalTok{ Data\_FIES }\SpecialCharTok{\%\textgreater{}\%}
  \CommentTok{\# Place the dependent variable in the first column and delete the unique value}
  \FunctionTok{select}\NormalTok{(Total.Number.of.Family.members, }\FunctionTok{everything}\NormalTok{(), }\SpecialCharTok{{-}}\NormalTok{Region) }\SpecialCharTok{\%\textgreater{}\%}
  \CommentTok{\# Convert categorical variables into factors}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{Household.Head.Sex =} \FunctionTok{as.factor}\NormalTok{(Household.Head.Sex),}
    \AttributeTok{Type.of.Household =} \FunctionTok{as.factor}\NormalTok{(Type.of.Household),}
    \AttributeTok{Electricity =} \FunctionTok{as.factor}\NormalTok{(Electricity)) }\SpecialCharTok{\%\textgreater{}\%}
  \CommentTok{\# Remove Missing Values}
  \FunctionTok{drop\_na}\NormalTok{()}
\NormalTok{FIES\_saved }\OtherTok{\textless{}{-}}\NormalTok{ FIES }\CommentTok{\# Used for model fitting}
\end{Highlighting}
\end{Shaded}

The dependent variable and independent variables are shown as below:

\textbf{Dependent Variable}:

\begin{itemize}
\tightlist
\item
  \textbf{Total.Number.of.Family.members}: Number of people living in
  the house.
\end{itemize}

\textbf{Independent Variables}:

\begin{itemize}
\item
  \textbf{Total.Household.Income}: Annual household income (in
  Philippine peso)
\item
  \textbf{Total.Food.Expenditure}: Annual expenditure by the household
  on food (in Philippine peso)
\item
  \textbf{Household.Head.Sex}: Head of the households sex
\item
  \textbf{Household.Head.Age}: Head of the households age (in years)
\item
  \textbf{Type.of.Household}: Relationship between the group of people
  living in the house
\item
  \textbf{House.Floor.Area}: Floor area of the house (in \(m^2\))
\item
  \textbf{House.Age}: Age of the building (in years)
\item
  \textbf{Number.of.bedrooms}: Number of bedrooms in the house
\item
  \textbf{Electricity}: Does the house have electricity? (1=Yes, 0=No)
\end{itemize}

\hypertarget{exploratory-data-analysis}{%
\section{Exploratory Data Analysis}\label{exploratory-data-analysis}}

Then we can check the data structure and get summary statistics of all
variables:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(FIES) }\CommentTok{\# Check data structure }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
'data.frame':   1887 obs. of  10 variables:
 $ Total.Number.of.Family.members: int  10 8 5 6 6 5 5 5 8 2 ...
 $ Total.Household.Income        : int  89359 108400 51982 76623 135232 73522 60369 60146 103365 53395 ...
 $ Total.Food.Expenditure        : int  54537 56611 30827 43639 59614 47563 48962 47482 55666 18361 ...
 $ Household.Head.Sex            : Factor w/ 2 levels "Female","Male": 1 2 2 2 2 2 1 2 2 2 ...
 $ Household.Head.Age            : int  34 55 26 53 55 38 50 32 49 60 ...
 $ Type.of.Household             : Factor w/ 3 levels "Extended Family",..: 2 2 2 2 2 2 2 2 2 2 ...
 $ House.Floor.Area              : int  64 60 48 42 56 56 48 42 48 20 ...
 $ House.Age                     : int  11 13 13 5 5 8 5 13 3 19 ...
 $ Number.of.bedrooms            : int  1 3 1 2 2 1 1 1 2 1 ...
 $ Electricity                   : Factor w/ 2 levels "0","1": 1 2 1 1 2 2 1 1 1 2 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(FIES) }\CommentTok{\# Get summary statistics of all variables  }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
 Total.Number.of.Family.members Total.Household.Income Total.Food.Expenditure
 Min.   : 1.000                 Min.   :  16238        Min.   :  3704        
 1st Qu.: 3.000                 1st Qu.:  85545        1st Qu.: 38311        
 Median : 4.000                 Median : 131806        Median : 54594        
 Mean   : 4.677                 Mean   : 214058        Mean   : 64113        
 3rd Qu.: 6.000                 3rd Qu.: 249176        3rd Qu.: 77068        
 Max.   :16.000                 Max.   :2598050        Max.   :363572        
 Household.Head.Sex Household.Head.Age
 Female: 400        Min.   :15.00     
 Male  :1487        1st Qu.:41.00     
                    Median :51.00     
                    Mean   :51.52     
                    3rd Qu.:61.00     
                    Max.   :95.00     
                              Type.of.Household House.Floor.Area   House.Age   
 Extended Family                       : 567    Min.   : 10.00   Min.   : 0.0  
 Single Family                         :1311    1st Qu.: 30.00   1st Qu.:10.0  
 Two or More Nonrelated Persons/Members:   9    Median : 50.00   Median :16.0  
                                                Mean   : 59.81   Mean   :19.5  
                                                3rd Qu.: 80.00   3rd Qu.:26.0  
                                                Max.   :600.00   Max.   :95.0  
 Number.of.bedrooms Electricity
 Min.   :0.000      0: 257     
 1st Qu.:1.000      1:1630     
 Median :2.000                 
 Mean   :1.945                 
 3rd Qu.:2.000                 
 Max.   :8.000                 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dim}\NormalTok{(FIES) }\CommentTok{\# Check dataset dimensions (number of rows and columns)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
[1] 1887   10
\end{verbatim}

\hypertarget{numerical-summaries-and-data-visualization}{%
\subsection{Numerical summaries and Data
visualization}\label{numerical-summaries-and-data-visualization}}

Now we can take a look at the numerical summaries and data visualization
of \textbf{dependent variable} shown in the following tables and plots:

\hypertarget{tbl-y}{}
\begin{table}
\caption{\label{tbl-y}Summary statistics for `Total.Number.of.Family.members' }\tabularnewline

\fontsize{12.0pt}{14.4pt}\selectfont
\begin{tabular*}{\linewidth}{@{\extracolsep{\fill}}rrrrrrr}
\toprule
Mean & Median & Std. Dev & Minimum & Maximum & Interquartile Range & Sample Size \\ 
\midrule\addlinespace[2.5pt]
4.68 & 4.00 & 2.30 & 1.00 & 16.00 & 3.00 & 1,887.00 \\ 
\bottomrule
\end{tabular*}
\end{table}

\begin{figure}[H]

{\centering \includegraphics{Group_03_Analysis_files/figure-pdf/fig-y-1.pdf}

}

\caption{\label{fig-y}Histogram of `Total.Number.of.Family.members'}

\end{figure}

From Table~\ref{tbl-y}, we can see our dataset includes 1887 samples,
which is a sufficiently large sample size to ensure reliability. The
mean value (4.68) and median (4.00) are very close, suggesting a roughly
symmetric distribution. However, the median is slightly lower than the
mean hints at a mild right skew in the data. The standard deviation
(2.30) indicates moderate variability around the mean.

Figure~\ref{fig-y} shows a strongly right-skewed distribution of
frequency data. The highest bar (around 300) is concentrated on the left
side of the x-axis, indicating that most values are in the lower ranges.
The frequency sharply decreased toward the right, with the far-right
bars approaching 0, shows that rare occurrences in higher-value
intervals.

Then check the variance of the dependent variable and compare with the
mean:

\begin{verbatim}
mean = 4.677266 
\end{verbatim}

\begin{verbatim}
var = 5.28232 
\end{verbatim}

\begin{verbatim}
var_ratio = 1.129361 
\end{verbatim}

var/mean=5.28/4.68=1.13 indicates that there is no overdispersion
problem, so Poisson regression model may be appropriate.

Then we separate independent variables into categorical variables and
numerical variables for analysis.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Categorical Variables}
\end{enumerate}

\hypertarget{tbl-y-sex}{}
\begin{table}
\caption{\label{tbl-y-sex}Summary statistics on `Total.Number.of.Family.members' by
`Household.Head.Sex' }\tabularnewline

\fontsize{9.0pt}{10.8pt}\selectfont
\begin{tabular*}{0.9\linewidth}{@{\extracolsep{\fill}}crrrrrrr}
\toprule
 & \multicolumn{7}{c}{Family Size Summary} \\ 
\cmidrule(lr){2-8}
Household.Head.Sex & Mean & Median & Std. Dev & Min & Max & IQR & Sample \\ 
\midrule\addlinespace[2.5pt]
Female & 3.83 & 3.00 & 2.33 & 1.00 & 15.00 & 3.00 & 400.00 \\ 
Male & 4.91 & 5.00 & 2.23 & 1.00 & 16.00 & 3.00 & 1,487.00 \\ 
\bottomrule
\end{tabular*}
\end{table}

\begin{figure}[H]

{\centering \includegraphics{Group_03_Analysis_files/figure-pdf/fig-y-sex-1.pdf}

}

\caption{\label{fig-y-sex}Boxplot of `Total.Number.of.Family.members' by
`Household.Head.Sex'}

\end{figure}

Table~\ref{tbl-y-sex} compares the `Total.Number.of.Family.members'
between female-headed and male-headed households. Female-headed
households exhibit smaller family size, with a mean of 3.83 and a median
of 3.00, while male-headed households show significantly larger families
(mean = 4.91, median = 5.00). Despite similar variability in both groups
(standard deviations of nearly 2.3), the male-headed households display
a broader range. Notably, the dataset is heavily skewed toward
male-headed households (1487 samples vs.~400 female samples), which
could influence the result. Both groups share identical interquartile
ranges (IQR = 3.00), suggesting comparable central clustering of data.

Figure~\ref{fig-y-sex} shows that male-headed households exhibit a
higher median family size of 5 members, compared to female-headed
households with a median of 4 members. Both groups shows moderate
variability in their distribution, but male-headed families display a
wider range, with extreme outliers reaching up to 16 members which
higher than the maximum of 15 members observed in female-headed
households. This visualizes the tendency for male-led families to hold a
larger household size.

\hypertarget{tbl-y-household}{}
\begin{table}
\caption{\label{tbl-y-household}Summary statistics on `Total.Number.of.Family.members' by
`Type.of.Household' }\tabularnewline

\fontsize{9.0pt}{10.8pt}\selectfont
\begin{tabular*}{0.9\linewidth}{@{\extracolsep{\fill}}crrrrrrr}
\toprule
 & \multicolumn{7}{c}{Household Summary} \\ 
\cmidrule(lr){2-8}
Type.of.Household & Mean & Median & Std. Dev & Min & Max & IQR & Sample Size \\ 
\midrule\addlinespace[2.5pt]
Single Family & 4.14 & 4.00 & 2.03 & 1.00 & 13.00 & 2.00 & 1,311.00 \\ 
Extended Family & 5.88 & 5.00 & 2.40 & 2.00 & 16.00 & 3.00 & 567.00 \\ 
Two or More Nonrelated Persons/Members & 6.89 & 6.00 & 2.80 & 4.00 & 12.00 & 2.00 & 9.00 \\ 
\bottomrule
\end{tabular*}
\end{table}

\begin{figure}[H]

{\centering \includegraphics{Group_03_Analysis_files/figure-pdf/fig-y-household-1.pdf}

}

\caption{\label{fig-y-household}Boxplot of
`Total.Number.of.Family.members' by `Type.of.Household'}

\end{figure}

Table~\ref{tbl-y-household} summarizes family size statistics across
three household types. Single-family households have the smallest
average family size (mean = 4.14, median = 4.00) with a large sample
size (1311). Extended families show significantly larger family sizes
(mean=5.88, median = 5.00) and a broader spread (max = 16). Households
with two or more unrelated members report the highest average (mean =
6.89, median - 6.00), but with a extremely small sample size (9) weakens
reliability.

Figure~\ref{fig-y-household} shows that extended families exhibit the
highest median family size (5) with a broader range which is up to 16
members, indicating potential outliers. Single families shows a lower
median (4) and tighter clustering of data. It reflects a more consistent
household size. Households with two or more unrelated members have a
median of 6 members. However it only has a sample size of 9 which
weakens the reliability of this category.

\hypertarget{tbl-y-electricity}{}
\begin{table}
\caption{\label{tbl-y-electricity}Summary statistics on `Total.Number.of.Family.members' by `Electricity' }\tabularnewline

\fontsize{9.0pt}{10.8pt}\selectfont
\begin{tabular*}{0.9\linewidth}{@{\extracolsep{\fill}}crrrrrrr}
\toprule
Electricity & Mean & Median & Std & Min & Max & IQ & Sample \\ 
\midrule\addlinespace[2.5pt]
0 & 4.70 & 5.00 & 2.47 & 1.00 & 12.00 & 3.00 & 257.00 \\ 
1 & 4.67 & 4.00 & 2.27 & 1.00 & 16.00 & 3.00 & 1,630.00 \\ 
\bottomrule
\end{tabular*}
\end{table}

\begin{figure}[H]

{\centering \includegraphics{Group_03_Analysis_files/figure-pdf/fig-y-electricity-1.pdf}

}

\caption{\label{fig-y-electricity}Boxplot of
`Total.Number.of.Family.members' by `Electricity'}

\end{figure}

From Table~\ref{tbl-y-electricity}, we can see households with
electricity (1,630) are about six times more than those without (257).
The mean values are nearly identical (4.70 vs.~4.67), but the median is
slightly higher for households without electricity (5.00 vs.~4.00). The
standard deviation is also slightly larger in the non-electric group
(2.47 vs.~2.27), indicating a bit more variability. The maximum value is
higher in the electricity group (16.00 vs.~12.00), suggesting a wider
range. Both groups have the same interquartile range (3.00), meaning
their middle 50\% distributions are similar. These differences can be
visualized more clearly with boxplots.

Figure~\ref{fig-y-electricity} shows that households without electricity
tend to have a slightly larger median family size compared to those with
electricity. However, the distributions of family sizes in both groups
are quite similar. The spread of family sizes in both groups is also
comparable, as indicated by the interquartile range. Additionally, both
groups exhibit several outliers, representing families with unusually
large sizes, as shown by the points beyond the ``whiskers'' of the
boxplots.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  \textbf{Numerical Variables}
\end{enumerate}

\begin{figure}[H]

{\centering \includegraphics{Group_03_Analysis_files/figure-pdf/fig-his-num-1.pdf}

}

\caption{\label{fig-his-num}Histograms for Numerical Variables}

\end{figure}

From Figure~\ref{fig-his-num}, we can see the distributions of
`Total.Household.Income', `Total.Food.Expenditure', and
`House.Floor.Area' are right-skewed, so applying a log transformation
would be beneficial when fitting a Poisson model.

``Household.Head.Age'' follows an approximately normal distribution,
with most household heads falling within the 30-60 age range. This
suggests that middle-aged individuals are the primary decision-makers in
households.

The distribution of `House.Floor.Area' is strongly right-skewed, with
most houses having relatively small areas, while a few have
significantly larger ones. The scarcity of large houses may be due to
their higher costs.

The distribution of `House.Age' exhibits a slight bimodal pattern,
indicating the presence of two types of houses: newly houses and older
houses.

The `Number.of.bedrooms' is a discrete variable, with most houses having
2 or 3 bedrooms, while houses with 4 or more bedrooms are less common.
So we can covert the `Number.of.bedrooms' into categorical variable:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Convert \textquotesingle{}Number.of.bedrooms\textquotesingle{} to categorical variable}
\NormalTok{FIES}\SpecialCharTok{$}\NormalTok{Bedroom.Category }\OtherTok{\textless{}{-}} \FunctionTok{cut}\NormalTok{(FIES}\SpecialCharTok{$}\NormalTok{Number.of.bedrooms, }
         \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{3}\NormalTok{, }\ConstantTok{Inf}\NormalTok{), }
         \AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Small"}\NormalTok{, }\StringTok{"Medium"}\NormalTok{, }\StringTok{"Large"}\NormalTok{),}\AttributeTok{right =} \ConstantTok{TRUE}\NormalTok{)}
\CommentTok{\# Convert categorical variable into factor}
\NormalTok{FIES}\SpecialCharTok{$}\NormalTok{Bedroom.Category }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(FIES}\SpecialCharTok{$}\NormalTok{Bedroom.Category)}
\end{Highlighting}
\end{Shaded}

Then we can use the heat map to check the correlation between numerical
variables and dependent variable:

\begin{figure}[H]

{\centering \includegraphics{Group_03_Analysis_files/figure-pdf/fig-corr-num-1.pdf}

}

\caption{\label{fig-corr-num}Heat map for numerical variables by
`Total.Number.of.Family.members'}

\end{figure}

From Figure~\ref{fig-corr-num}, we can see there is a strong correlation
between `Total.Household.Income' and `Total.Food.Expenditure'. We will
address this issue in the subsequent modeling process.
`Total.Number.of.Family.Members' shows a strong correlation with
`Total.Food.Expenditure', while `Household.Head.Age' and `House.Age'
have a slight negative correlation with
`Total.Number.of.Family.Members'. There is also some correlation between
`Total.Household.Income' and `Number.of.bedrooms',
`Total.Household.Income' and `House.Floor.Area',
`Total.Food.Expenditure' and `Number.of.bedrooms', and
`House.Floor.Area' and `Number.of.bedrooms'.

\hypertarget{formal-data-analysis}{%
\section{Formal Data Analysis}\label{formal-data-analysis}}

Since the dependent variable `Total.Number.of.Family.members' is a
typical count variable with a mean and variance that are approximately
equal, Poisson regression was chosen for modeling. Based on the results
of EDA, some variables were log-transformed to improve linear
relationships and reduce heteroscedasticity. All selected variables were
then included in the model, and stepwise regression using
drop1(poisson\_model, test = ``F'') was performed to assess variable
significance, gradually eliminating insignificant variables to ensure
the final model's robustness and explanatory power.

Fit the first Poisson regression model:

\[
y_{FS} = \beta_0 + \beta_1 \log[f_{In}(x)] + \beta_2 \log[f_{FE}(x)] + \beta_3 [f_{HS}(x)] + \beta_4 [f_{HeA}(x)] + \beta_5 [f_{HT}(x)] + \beta_6 \log[f_{FA}(x)] + \beta_7 \log[f_{HoA}(x)] + \beta_8 [f_{Bed}(x)] + \beta_9 [f_{El}(x)]
\]

where

\begin{itemize}
\item
  \(y_{FS}\): The expected value of family size (dependent variable).
\item
  \(\log[f_{In}(x)]\): The logarithm of household income, measuring the
  economic level of the family.
\item
  \(\log[f_{FE}(x)]\): The logarithm of food expenditure, representing
  the household's spending on food.
\item
  \(f_{HS}(x)\): The gender of the household head (categorical variable,
  usually 0 for female and 1 for male).
\item
  \(f_{HeA}(x)\): The age of the household head (continuous variable),
  indicating the effect of the household head's age on family size.
\item
  \(f_{HT}(x)\): The type of household (categorical variable),
  indicating different family structures such as single-parent or
  nuclear families.
\item
  \(\log\left[f_{FA}(x)\right]\): The logarithm of the floor area of the
  household (continuous variable), measuring the size of the living
  space.
\item
  \(\log[f_{HoA}(x)]\): The logarithm of house age (with +1 to avoid
  taking the logarithm of 0), measuring the age of the dwelling.
\item
  \(f_{Bed}(x)\): The number of bedrooms in the household (continuous
  variable), reflecting the size of the dwelling.
\item
  \(f_{EL}(x)\): Whether the household has access to electricity (0 =
  no, 1 = yes), reflecting the household's infrastructure.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{poisson\_model1 }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(Family\_Size }\SpecialCharTok{\textasciitilde{}} 
                       \FunctionTok{log}\NormalTok{(Income) }\SpecialCharTok{+}
                       \FunctionTok{log}\NormalTok{(Food\_Exp) }\SpecialCharTok{+}
\NormalTok{                       Head\_Sex }\SpecialCharTok{+}
\NormalTok{                       Head\_Age }\SpecialCharTok{+} 
\NormalTok{                       Household\_Type }\SpecialCharTok{+}
                       \FunctionTok{log}\NormalTok{(Floor\_Area) }\SpecialCharTok{+}
                       \FunctionTok{log}\NormalTok{(House\_Age}\FloatTok{+0.1}\NormalTok{) }\SpecialCharTok{+}
\NormalTok{                       Bedrooms }\SpecialCharTok{+}
\NormalTok{                       Electricity, }
                     \AttributeTok{family =} \FunctionTok{poisson}\NormalTok{(}\AttributeTok{link =} \StringTok{"log"}\NormalTok{),}
                     \AttributeTok{data =}\NormalTok{ FIES)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Single term deletions

Model:
Family_Size ~ log(Income) + log(Food_Exp) + Head_Sex + Head_Age + 
    Household_Type + log(Floor_Area) + log(House_Age + 0.1) + 
    Bedrooms + Electricity
                     Df Deviance    AIC  F value    Pr(>F)    
<none>                    1218.5 7450.3                       
log(Income)           1   1315.2 7545.0 148.8405 < 2.2e-16 ***
log(Food_Exp)         1   1588.8 7818.6 570.1446 < 2.2e-16 ***
Head_Sex              1   1244.6 7474.4  40.1738 2.903e-10 ***
Head_Age              1   1241.2 7471.0  34.9168 4.077e-09 ***
Household_Type        2   1362.3 7590.1 110.6954 < 2.2e-16 ***
log(Floor_Area)       1   1218.7 7448.4   0.2034    0.6520    
log(House_Age + 0.1)  1   1228.7 7458.5  15.6560 7.880e-05 ***
Bedrooms              1   1218.5 7448.3   0.0287    0.8654    
Electricity           1   1229.0 7458.7  16.1106 6.210e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

For `Floor\_Area', since it is a continuous variable, a log
transformation was applied during the EDA process to improve linearity
and reduce heteroscedasticity. However, it remained insignificant in the
Poisson regression model even after transformation, so it is considered
for removal. As for `Bedrooms', it is a discrete integer variable with a
large number of zero values. Given the potential categorical effect,
converting it into a categorical variable may be more appropriate to
better capture its impact on `Family\_Size'.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{FIES}\SpecialCharTok{$}\NormalTok{Bedroom.Category }\OtherTok{\textless{}{-}} \FunctionTok{cut}\NormalTok{(FIES}\SpecialCharTok{$}\NormalTok{Bedrooms, }
                             \AttributeTok{breaks =} \FunctionTok{c}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{3}\NormalTok{, }\ConstantTok{Inf}\NormalTok{), }
                             \AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Small"}\NormalTok{, }\StringTok{"Medium"}\NormalTok{, }\StringTok{"Large"}\NormalTok{),}
                             \AttributeTok{right =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{FIES}\SpecialCharTok{$}\NormalTok{Bedroom.Category }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(FIES}\SpecialCharTok{$}\NormalTok{Bedroom.Category)}
\end{Highlighting}
\end{Shaded}

Fit a linear regression model with `Bedroom.Category' and observe that
the results show the category has a certain significance:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model\_cat }\OtherTok{\textless{}{-}} \FunctionTok{lm}\NormalTok{(Family\_Size }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Bedroom.Category, }\AttributeTok{data =}\NormalTok{ FIES)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model\_summary }\OtherTok{\textless{}{-}} \FunctionTok{summary}\NormalTok{(model\_cat)}\SpecialCharTok{$}\NormalTok{coefficients}
\FunctionTok{library}\NormalTok{(knitr)}
\FunctionTok{kable}\NormalTok{(model\_summary, }\AttributeTok{caption =} \StringTok{"Model Coefficients and Significance"}\NormalTok{, }\AttributeTok{format =} \StringTok{"latex"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{table}

\caption{Model Coefficients and Significance}
\centering
\begin{tabular}[t]{l|r|r|r|r}
\hline
  & Estimate & Std. Error & t value & Pr(>|t|)\\
\hline
(Intercept) & 4.3961708 & 0.0878516 & 50.040880 & 0.0000000\\
\hline
Bedroom.CategoryMedium & 0.4139795 & 0.1124417 & 3.681725 & 0.0002382\\
\hline
Bedroom.CategoryLarge & 0.6246625 & 0.2100237 & 2.974248 & 0.0029744\\
\hline
\end{tabular}
\end{table}

Then we can fit a Poisson regression model with `Bedroom.Category' the
same as above:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{poisson\_model\_cat }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(Family\_Size }\SpecialCharTok{\textasciitilde{}} 
                       \FunctionTok{log}\NormalTok{(Income) }\SpecialCharTok{+}
                       \FunctionTok{log}\NormalTok{(Food\_Exp) }\SpecialCharTok{+}
\NormalTok{                       Head\_Sex }\SpecialCharTok{+}
\NormalTok{                       Head\_Age }\SpecialCharTok{+} 
\NormalTok{                       Household\_Type }\SpecialCharTok{+}
                       \FunctionTok{log}\NormalTok{(House\_Age}\SpecialCharTok{+}\DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
\NormalTok{                       Bedroom.Category }\SpecialCharTok{+}
\NormalTok{                       Electricity, }
                     \AttributeTok{family =} \FunctionTok{poisson}\NormalTok{(}\AttributeTok{link =} \StringTok{"log"}\NormalTok{),}
                     \AttributeTok{data =}\NormalTok{ FIES) }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Single term deletions

Model:
Family_Size ~ log(Income) + log(Food_Exp) + Head_Sex + Head_Age + 
    Household_Type + log(House_Age + 1) + Bedroom.Category + 
    Electricity
                   Df Deviance    AIC  F value    Pr(>F)    
<none>                  1216.0 7447.8                       
log(Income)         1   1314.7 7544.4 152.1694 < 2.2e-16 ***
log(Food_Exp)       1   1584.2 7814.0 567.9627 < 2.2e-16 ***
Head_Sex            1   1241.2 7471.0  38.8521 5.632e-10 ***
Head_Age            1   1239.4 7469.1  35.9972 2.366e-09 ***
Household_Type      2   1359.7 7587.5 110.8329 < 2.2e-16 ***
log(House_Age + 1)  1   1226.6 7456.3  16.2519 5.767e-05 ***
Bedroom.Category    2   1218.5 7446.2   1.8675    0.1548    
Electricity         1   1227.7 7457.4  17.9213 2.414e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

After converting `Bedrooms' into a categorical variable and refitting
the model, it remained insignificant, so it was ultimately removed.

Fit the second Poisson regression model:

\[
y_{FS} = \beta_0 + \beta_1 \log[f_{In}(x)] + \beta_2 \log[f_{FE}(x)] + \beta_3 [f_{HS}(x)] + \beta_4 [f_{HeA}(x)] + \beta_5 [f_{HT}(x)] + \beta_6 \log[f_{HoA}(x)] + \beta_8 [f_{El}(x)]
\]

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{poisson\_model2 }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(Family\_Size }\SpecialCharTok{\textasciitilde{}} 
                          \FunctionTok{log}\NormalTok{(Income) }\SpecialCharTok{+}
                          \FunctionTok{log}\NormalTok{(Food\_Exp) }\SpecialCharTok{+}
\NormalTok{                          Head\_Sex }\SpecialCharTok{+}
\NormalTok{                          Head\_Age }\SpecialCharTok{+} 
\NormalTok{                          Household\_Type }\SpecialCharTok{+}
                          \FunctionTok{log}\NormalTok{(House\_Age}\SpecialCharTok{+}\DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
\NormalTok{                          Electricity, }
                        \AttributeTok{family =} \FunctionTok{poisson}\NormalTok{(}\AttributeTok{link =} \StringTok{"log"}\NormalTok{),}
                        \AttributeTok{data =}\NormalTok{ FIES)}
\end{Highlighting}
\end{Shaded}

Although the classification of `Household\_Type' is not significant
statistically, it is retained based on the theoretical justification
from the original data classification. This ensures that its impact is
still considered during model interpretation.

\begin{figure}[H]

{\centering \includegraphics{Group_03_Analysis_files/figure-pdf/fig-residual1-1.pdf}

}

\caption{\label{fig-residual1}The Pearson and deviance residuals against
the linear predictor}

\end{figure}

By plotting the QQ plots of Pearson and Deviance, we found that the data
conform to the normality assumption. To further assess whether there is
significant overdispersion in the Deviance distribution, we compared the
performance of the original Poisson model and the Quasi-Poisson model in
handling overdispersion. By comparing the standardized Pearson residuals
of both models, we found that the original Poisson model performed
better, indicating no significant overdispersion. Therefore, no
adjustment was made to the standard errors of the parameters, as
overdispersion was not evident.

\begin{verbatim}

Call:
glm(formula = Family_Size ~ log(Income) + log(Food_Exp) + Head_Sex + 
    Head_Age + Household_Type + log(House_Age + 1) + Electricity, 
    family = poisson(link = "log"), data = FIES)

Coefficients:
                                                       Estimate Std. Error
(Intercept)                                          -2.7453484  0.1956354
log(Income)                                          -0.2731779  0.0218092
log(Food_Exp)                                         0.7355788  0.0313499
Head_SexMale                                          0.1454000  0.0235193
Head_Age                                             -0.0041994  0.0007119
Household_TypeSingle Family                          -0.2847395  0.0193537
Household_TypeTwo or More Nonrelated Persons/Members  0.0961818  0.1043781
log(House_Age + 1)                                   -0.0512741  0.0128593
Electricity1                                         -0.1092392  0.0271865
                                                     z value Pr(>|z|)    
(Intercept)                                          -14.033  < 2e-16 ***
log(Income)                                          -12.526  < 2e-16 ***
log(Food_Exp)                                         23.464  < 2e-16 ***
Head_SexMale                                           6.182 6.32e-10 ***
Head_Age                                              -5.899 3.66e-09 ***
Household_TypeSingle Family                          -14.712  < 2e-16 ***
Household_TypeTwo or More Nonrelated Persons/Members   0.921    0.357    
log(House_Age + 1)                                    -3.987 6.68e-05 ***
Electricity1                                          -4.018 5.87e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 0.6580882)

    Null deviance: 2130.1  on 1886  degrees of freedom
Residual deviance: 1218.5  on 1878  degrees of freedom
AIC: 7446.2

Number of Fisher Scoring iterations: 4
\end{verbatim}

\begin{figure}[H]

{\centering \includegraphics{Group_03_Analysis_files/figure-pdf/fig-likelihood-1.pdf}

}

\caption{\label{fig-likelihood}Regular likelihood and Quasi-likelihood}

\end{figure}

Based on the model comparison and LRT test results, and considering the
high correlation observed in the EDA heatmap, an interaction term
between `Income' and `Food\_Exp' was introduced. After comparing the
original model with the model including the interaction term, it was
found that the Deviance decreased by 47.118 after adding the interaction
term, indicating that the inclusion of the interaction term
significantly improved the model's fit. Therefore, the conclusion can be
made that introducing the interaction term effectively enhanced the
model's explanatory power and fit the final Poisson regression model:

\[
y_{FS} = \beta_0 + \beta_1 \log[f_{In}(x)] + \beta_2 \log[f_{FE}(x)] + \beta_3 \log[f_{In}(x)]\log[f_{FE}(x)] + \beta_4 [f_{HS}(x)] + \beta_5 [f_{HeA}(x)] + \beta_6 [f_{HT}(x)] + \beta_7 \log[f_{HoA}(x)] + \beta_8 [f_{El}(x)]
\]

where

\begin{itemize}
\item
  \(y_{FS}\): The expected value of family size (dependent variable).
\item
  \(\log[f_{In}(x)]\): The logarithm of household income, measuring the
  economic level of the family.
\item
  \(\log[f_{FE}(x)]\): The logarithm of food expenditure, representing
  the household's spending on food.
\item
  \(\log[f_{In}(x)]\log[f_{FE}(x)]\): The interaction term between
  income and food expenditure, measuring their joint effect on family
  size.
\item
  \(f_{HS}(x)\): The gender of the household head (categorical variable,
  usually 0 for female and 1 for male).
\item
  \(f_{HeA}(x)\): The age of the household head (continuous variable),
  indicating the effect of the household head's age on family size.
\item
  \(f_{HT}(x)\): The type of household (categorical variable),
  indicating different family structures such as single-parent or
  nuclear families.
\item
  \(\log[f_{HoA}(x)]\): The logarithm of house age (with +1 to avoid
  taking the logarithm of 0), measuring the age of the dwelling.
\item
  \(f_{EL}(x)\): Whether the household has access to electricity (0 =
  no, 1 = yes), reflecting the household's infrastructure.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{poisson\_model4 }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(Family\_Size }\SpecialCharTok{\textasciitilde{}} 
                      \FunctionTok{log}\NormalTok{(Income) }\SpecialCharTok{*} \FunctionTok{log}\NormalTok{(Food\_Exp) }\SpecialCharTok{+}
\NormalTok{                      Head\_Sex }\SpecialCharTok{+} 
\NormalTok{                      Head\_Age }\SpecialCharTok{+} 
\NormalTok{                      Household\_Type }\SpecialCharTok{+}
                      \FunctionTok{log}\NormalTok{(House\_Age }\SpecialCharTok{+} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
\NormalTok{                      Electricity, }
                      \AttributeTok{family =} \FunctionTok{poisson}\NormalTok{(}\AttributeTok{link =} \StringTok{"log"}\NormalTok{),}
                      \AttributeTok{data =}\NormalTok{ FIES)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
Analysis of Deviance Table

Model 1: Family_Size ~ log(Income) + log(Food_Exp) + Head_Sex + Head_Age + 
    Household_Type + log(House_Age + 1) + Electricity
Model 2: Family_Size ~ log(Income) * log(Food_Exp) + Head_Sex + Head_Age + 
    Household_Type + log(House_Age + 1) + Electricity
  Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    
1      1878     1218.5                          
2      1877     1171.3  1   47.118 6.685e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{figure}[H]

{\centering \includegraphics{Group_03_Analysis_files/figure-pdf/fig-residual2-1.pdf}

}

\caption{\label{fig-residual2}The Pearson and deviance residuals against
the linear predictor}

\end{figure}

The QQ plots of the Pearson and Deviance both conform to the normality
assumption and there is no obvious overdispersion in the Residuals plot.

\hypertarget{conclusion}{%
\section{Conclusion}\label{conclusion}}

Based on the results of Relative Risk(RR) from the model, the following
key conclusions can be summarized:

\begin{table}
\centering
\caption{Poisson Model Coefficients and Relative Risks}
\centering
\begin{tabular}[t]{l|r|r}
\hline
term & estimate & RR\\
\hline
(Intercept) & -21.7708565 & 0.0000000\\
\hline
log(Income) & 1.3324561 & 3.7903412\\
\hline
log(Food\_Exp) & 2.4203371 & 11.2496508\\
\hline
Head\_SexMale & 0.1377819 & 1.1477252\\
\hline
Head\_Age & -0.0037134 & 0.9962935\\
\hline
Household\_TypeSingle Family & -0.2826811 & 0.7537601\\
\hline
Household\_TypeTwo or More Nonrelated Persons/Members & 0.0818574 & 1.0853010\\
\hline
log(House\_Age + 1) & -0.0553559 & 0.9461484\\
\hline
Electricity1 & -0.1498882 & 0.8608042\\
\hline
log(Income):log(Food\_Exp) & -0.1416451 & 0.8679292\\
\hline
\end{tabular}
\end{table}

From the results, we can see:

\begin{itemize}
\item
  Income's Impact on Family Size: When income increases by 1\%, the
  average family size increases by approximately 3.79 times. This
  indicates a positive correlation between income and family size,
  suggesting that higher income may be associated with larger families.
\item
  Food Expenditure's Impact on Family Size: When food expenditure
  increases by 1\%, the average family size increases by approximately
  11.25 times. This suggests that higher food spending is closely
  related to an increase in family size.
\item
  House Age's Impact on Family Size: When house age increases by 1\%,
  the average family size decreases by approximately 5.39\%. This
  implies that older houses may be associated with smaller family sizes,
  possibly due to living conditions or other factors.
\item
  Interaction Between Income and Food Expenditure: When both income and
  food expenditure increase by 1\%, the average family size decreases by
  approximately 13.21\%. This suggests that while both variables have a
  positive individual effect, their interaction shows a negative
  association, possibly indicating that higher income combined with
  higher food expenditure may not lead to a larger family size.
\item
  Head Sex's Impact on Family Size: Families with male heads tend to
  have approximately 15\% more members than those with female heads.
  This indicates that families with male heads may be larger than those
  with female heads.
\item
  Head Age's Impact on Family Size: For each additional year in the
  head's age, the average family size decreases by approximately 0.4\%.
  This suggests that older heads of households may have smaller
  families.
\item
  Household Type's Impact on Family Size: If the household type is a
  single-parent family, the average family size is about 25\% smaller
  compared to other household types. Single-parent families generally
  have smaller family sizes.
\end{itemize}

In conclusion, these results show that family size is closely related to
various factors, particularly income, food expenditure, head sex, and
household type. Changes in family size are influenced not only by
individual variables but also by the interactions between them.



\end{document}
