---
title: "Analysis of the FIES recorded in the Philippines"
author: "Group_03"
number-sections: true
format: 
  html:
    embed-resources: true
    code-tools: true
  pdf: default
editor_options: 
  chunk_output_type: console
execute:
  echo: false
  eval: true
  warning: false
  message: false
---

```{r}
library(ggplot2)
library(tidyverse)
library(gt)
library(patchwork)
library(gridExtra)
library(moderndive)
```

# Introduction

# Data Cleaning

```{r}
# Read the data set
Data_FIES <- read.csv("dataset03.csv")
# Tidy the data
Data_tidy <- Data_FIES %>%
  # Place the dependent variable in the first column and delete the unique value
  select(Total.Number.of.Family.members, everything(), -Region) %>%
  # Convert categorical variables into factors
  mutate(
    Household.Head.Sex = as.factor(Household.Head.Sex),
    Type.of.Household = as.factor(Type.of.Household),
  ) %>%
  # Remove Missing Values
  drop_na()

```

# Exploratory Data Analysis

# Formal Data Analysis

# Conclusion
